### ISSUE TITLE
Using predictable/constant cryptographic key when creating and verifing Json Web Token.

### ISSUE THREAD

**Issue by xubowenW** [zuihou/lamp-util#10]
Hi, we are a research group to help developers build secure applications. We designed a cryptographic misuse detector on Java language. We found your great public repository (i.e., lamp-cloud) from Github, and several security issues detected by our detector are shown in the following. The specific security issues we found are as follows:
(1) Location: lamp-core-3.7.0 Package: top.tangyh.basic.context Class: ContextConstant.class
Security issue: Using predictable/constant cryptographic key when creating and verifing Json Web Token.
(2) Location: lamp-util-3.7.0 Package: top.tangyh.basic.jwt.utils
Class: JwtUtil.class
Security issue: Using predictable/constant cryptographic key when creating and verifing Json Web Token.

![image](https://user-images.githubusercontent.com/40926753/188397641-5640895f-5351-4e9b-82e5-e624600aa371.png)
![image](https://user-images.githubusercontent.com/40926753/188397711-1683eaea-d587-43a8-821a-3f6170a61b8a.png)
![image](https://user-images.githubusercontent.com/40926753/188397953-cfd0ffc0-146f-49c4-af72-cb132a277ce2.png)
![image](https://user-images.githubusercontent.com/40926753/188398106-3e919d2f-56d7-4f07-8cd8-870d1e2b68e4.png)

**Comment by zuihou** [comment]
https://github.com/zuihou/lamp-util/commit/7f9416593e257234048b110036d8e6c40da0375c
